'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HimmelskoerperTypenTab
    Public Property ID As Integer
    Public Property Name As String

    Public Overridable Property HimmelskoerperTab As ICollection(Of HimmelskoerperTab) = New HashSet(Of HimmelskoerperTab)

End Class
