'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class KeplerDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=KeplerDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AufgabenTab() As DbSet(Of AufgabenTab)
    Public Overridable Property HimmelskoerperTab() As DbSet(Of HimmelskoerperTab)
    Public Overridable Property HimmelskoerperTypenTab() As DbSet(Of HimmelskoerperTypenTab)
    Public Overridable Property LaenderTab() As DbSet(Of LaenderTab)
    Public Overridable Property RaumschiffeTab() As DbSet(Of RaumschiffeTab)
    Public Overridable Property Sterne_Planeten_MondeTab() As DbSet(Of Sterne_Planeten_MondeTab)
    Public Overridable Property UmlaufbahnenTab() As DbSet(Of UmlaufbahnenTab)
    Public Overridable Property UrlSammlungenTab() As DbSet(Of UrlSammlungenTab)

End Class
