'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RaumschiffeTab
    Public Property Start_der_Mission As Date
    Public Property HimmelskoerperID As Integer
    Public Property Land_ID As Integer
    Public Property RaumschiffAufgaben_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab
    Public Overridable Property LaenderTab As LaenderTab
    Public Overridable Property AufgabenTab As ICollection(Of AufgabenTab) = New HashSet(Of AufgabenTab)

End Class
