'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class KeplerDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=KeplerDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AufgabenTab() As DbSet(Of AufgabenTab)
    Public Overridable Property BildTab() As DbSet(Of BildTab)
    Public Overridable Property HimmelskoerperTab() As DbSet(Of HimmelskoerperTab)
    Public Overridable Property HimmelskoerperTypenTab() As DbSet(Of HimmelskoerperTypenTab)
    Public Overridable Property LaenderTab() As DbSet(Of LaenderTab)
    Public Overridable Property RaumschiffeTab() As DbSet(Of RaumschiffeTab)
    Public Overridable Property SpektralklasseTab() As DbSet(Of SpektralklasseTab)
    Public Overridable Property Sterne_Planeten_MondeTab() As DbSet(Of Sterne_Planeten_MondeTab)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property UmlaufbahnenTab() As DbSet(Of UmlaufbahnenTab)

End Class
