'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sysdiagrams
    Public Property name As String
    Public Property principal_id As Integer
    Public Property diagram_id As Integer
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
