'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UmlaufbahnenTab
    Public Property Laenge_grosse_Halbachse_in_km As Double
    Public Property Exzentritzitaet As Double
    Public Property Umlaufdauer_in_Tagen As Double
    Public Property Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec As Double
    Public Property TrabantID As Integer
    Public Property Zentralobjekt_ID As Integer

    Public Overridable Property Trabant As HimmelskoerperTab
    Public Overridable Property Zentralkoerper As HimmelskoerperTab

End Class
