'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BildTab
    Public Property HimmelskoerperID As Integer
    Public Property Bilddaten As Byte()
    Public Property Himmelskoerper_ID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab

End Class
