'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sterne_Planeten_MondeTab
    Public Property Aequatordurchmesser_in_km As Double
    Public Property Polardurchmesser_in_km As Double
    Public Property Oberflaechentemperatur_in_K As Double
    Public Property Rotationsperiode_in_Stunden As Double
    Public Property Fallbeschleunigung_in_meter_pro_sec As Double
    Public Property Rotationsachsenneigung_in_Grad As Double
    Public Property HimmelskoerperID As Integer

    Public Overridable Property HimmelskoerperTab As HimmelskoerperTab

End Class
